### ISSUE TITLE
Roadmap for v0.1.0

### ISSUE THREAD

**Issue by KindlyFire** [TerbiumCMS/TerbiumCMS#1]
The first version of Terbium will support mandatory functions for a blogging engine:

- [ ] Initial blog setup (database configuration, administrator account creation and configuration for some basic blog settings like title, description)
- [ ] Admin back-end for post creation and management (raw text only at first, a good post editor will be added later)
- [ ] Public front-end displaying post lists or a single post
